services:
  - type: web
    name: rootzsu-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p logs
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
    
  - type: worker
    name: rootzsu-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p logs
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0